//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotWithDialog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOT_DOMAIN
    {
        public int DOMAIN_ID { get; set; }
        public string DOMAIN { get; set; }
        public Nullable<int> RECORD_STATUS { get; set; }
    }
}
