//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotWithDialog.Models
{
    using Microsoft.Bot.Builder.FormFlow;
    using Microsoft.Bot.Builder.FormFlow.Advanced;
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class BOT_CUSTOMERINFO
    {

        public int CUSTOMER_ID { get; set; }

        public Nullable<int> DOMAIN_ID { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
   
        public Nullable<int> RECORD_STATUS { get; set; }

        public static IForm<BOT_CUSTOMERINFO> BuildForm()
        {

            return new FormBuilder<BOT_CUSTOMERINFO>()
                .Message("Vui lòng cung cấp thông tin")
                .Field(nameof(NAME))
                .Field(nameof(EMAIL))
                .Field(nameof(PHONE))
                .Field(new FieldReflector<BOT_CUSTOMERINFO>(nameof(CUSTOMER_ID)).SetActive((state) => false))
                .Build();

        }

    }
}
