//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotWithDialog.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BotDBEntities : DbContext
    {
        public BotDBEntities()
            : base("name=BotDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOT_ANSWER> BOT_ANSWER { get; set; }
        public virtual DbSet<BOT_CUSTOMERINFO> BOT_CUSTOMERINFO { get; set; }
        public virtual DbSet<BOT_DOMAIN> BOT_DOMAIN { get; set; }
        public virtual DbSet<BOT_QUESTIONTYPE> BOT_QUESTIONTYPE { get; set; }
        public virtual DbSet<BOT_SCENARIO> BOT_SCENARIO { get; set; }
        public virtual DbSet<BOT_USER> BOT_USER { get; set; }
        public virtual DbSet<BOT_QUESTION> BOT_QUESTION { get; set; }
    }
}
